export const allbenefits = [
    {
        name: 'Crypto Creatures', 
        contractAddress : '0x9809abfc4319271259a340775ec03e9746b76068',
        collection: 'rewarding-renditions',
        chain: 'binance',
        mintPrice: 0.32,
        totalSize: 5000,
        unlockLevel: 2,
        earnDescription: 'Earn from 10% Direct + 8% Indirect',
        url: 'crypto_creatures',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct and 8% from second of Loyalty Reward System' },
            { content: '4 Stages of FREE BNB Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'orange',
        picture: 'crypto1',
    },
    {
        name: 'Neon Dreams', 
        contractAddress : '0x2945db324Ec216a5D5cEcE8B4D76f042553a213f',
        collection: 'rewarding-renditions',
        chain: 'binance',
        mintPrice: 0.64,
        totalSize: 5000,
        unlockLevel: 3,
        earnDescription: 'Earn from 10% Direct + (8% + 6%) Indirect',
        url: 'neon_dreams',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct, 8% from second and 6% from third level of Loyalty Reward System' },
            { content: '4 Stages of FREE BNB Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'neon',
        picture: 'neon1',
    },
    {
        name: 'Celestial Beings', 
        contractAddress : '0x54265672B480fF8893389F2c68caeF29C95c7BE2',
        collection: 'rewarding-renditions',
        chain: 'binance',
        mintPrice: 1.04,
        totalSize: 10000,
        unlockLevel: 4,
        earnDescription: 'Earn from 10% Direct + (8% + 6% + 5%) Indirect',
        url: 'celestial_beings',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct, 8% from second, 6% from third, and 5% from fourth level of Loyalty Reward System' },
            { content: '4 Stages of FREE BNB Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'flamingo',
        picture: 'celestial1',
    },
    {
        name: 'Artifacts of the Future', 
        contractAddress : '0x9BDa42900556fCce5927C1905084C4b3CffB23b0',
        collection: 'rewarding-renditions', 
        chain: 'binance',
        mintPrice: 1.49,
        totalSize: 20000,
        unlockLevel: 5,
        earnDescription: 'Earn from 10% Direct + (8% + 6% + 5% + 5%) Indirect',
        url: 'artifacts_of_the_future',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct, 8% from second, 6% from third, 5% from fourth and 5% from fifth level of Loyalty Reward System' },
            { content: '4 Stages of FREE BNB Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'apple',
        picture: 'artifacts1',
    },
    {
        name: 'Nomin', 
        contractAddress : '0x05e9d0Fa11eFF24F3c2fB0AcD381B6866CeF2a1C', 
        collection: 'mushroom-kingdom',
        chain: 'ethereum',
        mintPrice: 0.04,
        totalSize: 5000,
        unlockLevel: 2,
        earnDescription: 'Earn from 10% Direct + 8% Indirect',
        url: 'nomin',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct and 8% from second of Loyalty Reward System' },
            { content: '4 Stages of FREE ETH Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'orange',
        picture: 'nomin1',
    },
    {
        name: 'Grutzi', 
        contractAddress : '0x50Fb365F7B1c5CfaF3a0a9341029ABD0ce8e4f80',
        collection: 'mushroom-kingdom',
        chain: 'ethereum',
        mintPrice: 0.08,
        totalSize: 5000,
        unlockLevel: 3,
        earnDescription: 'Earn from 10% Direct + (8% + 6%) Indirect',
        url: 'grutzi',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct, 8% from second and 6% from third level of Loyalty Reward System' },
            { content: '4 Stages of FREE ETH Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'neon',
        picture: 'grutzi1',
    },
    {
        name: 'Hidoi', 
        contractAddress : '0x023803f52a5DD566AC1E6a3B06bCE8CD0d27a8a7',
        collection: 'mushroom-kingdom',
        chain: 'ethereum',
        mintPrice: 0.135,
        totalSize: 10000,
        unlockLevel: 4,
        earnDescription: 'Earn from 10% Direct + (8% + 6% + 5%) Indirect',
        url: 'hidoi',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct, 8% from second, 6% from third, and 5% from fourth level of Loyalty Reward System' },
            { content: '4 Stages of FREE ETH Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'flamingo',
        picture: 'hidoi1',
    },
    {
        name: 'Kaioji', 
        contractAddress : '0xa98d96E636123dFB35AB037d1E5a7B76a6e7e95B',
        collection: 'mushroom-kingdom', 
        chain: 'ethereum',
        mintPrice: 0.188,
        totalSize: 20000,
        unlockLevel: 5,
        earnDescription: 'EEarn from 10% Direct + (8% + 6% + 5% + 5%) Indirect',
        url: 'kaioji',
        benefits: [
            { content: 'Receive 5% Royalty on every resale of this NFT forever' },
            { content: 'Allows you to earn 10% from direct, 8% from second, 6% from third, 5% from fourth and 5% from fifth level of Loyalty Reward System' },
            { content: '4 Stages of FREE ETH Airdrops' },
            { content: '1 stage of FREE Nuva Token Airdrop' }
        ],
        buttonColor: 'apple',
        picture: 'kaioji1',
    }
];